version: '3'
services:

    # PHP service
    app:
        build:
            context: .
            dockerfile: php.Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # nginx service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/default.conf

    # MySQL service
    db:
        image: mysql
        container_name: db
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: on-failure
        ports:
            - "3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: YOUR_MYSQL_PASSWORD
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/

# Docker volumes
volumes:
    dbdata:
        driver: local
